services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
